### ISSUE TITLE
Update rancher-version annotation to include 2.7 versions in kubewarden-controller

### ISSUE THREAD

**Issue by jordojordo** [kubewarden/helm-charts#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to install the latest `kubewarden-controller` chart from the UI with a Rancher version `v2.7.0`, the latest versions of the chart do not appear. This is causing the installation to fail as the `kubewarden-crds` chart is not being auto-installed along with the controller.

I believe [this annotation](https://github.com/kubewarden/helm-charts/blob/e2fbce99b999a24923a00ec1bea404a4200e40e6/charts/kubewarden-controller/Chart.yaml#L43) needs to be updated to include 2.7.0 versions of Rancher, or rewritten to `>= 2.7.0-0 <= 2.7.100-0` as `v2.7.0` is the first with the extensions support.

### Expected Behavior

All of the latest versions should appear and should include the crd auto-install.

### Steps To Reproduce

1. With Rancher `v2.7.0` attempt to install Kubewarden from the UI guided steps

### Anything else?

![versions](https://user-images.githubusercontent.com/40806497/202754515-948a1734-3599-4906-81cd-e935aaa012d3.png)

___Response from chart fetch___
![response](https://user-images.githubusercontent.com/40806497/202755098-205d7be1-68c9-48fd-b504-6ed303d7f8d3.png)

**Comment by viccuad** [comment]
@jordojordo you are right, that was it! opened https://github.com/kubewarden/helm-charts/pull/156 to fix it.
