### ISSUE TITLE
Remove duplicated helm charts

### ISSUE THREAD

**Issue by flavio** [kubewarden/helm-charts#175]
Because of a small mistake in our automation pipeline (see https://github.com/kubewarden/helm-charts/pull/174) some of our helm charts had duplicates inside of their name.

Next time a new helm chart is going to be released, the fix from the previous PR will create new helm charts with proper name. Once that's done, we have to manually remove the charts with the ugly names.

**Comment by viccuad** [comment]
I suppose we should also push the old charts to the new ghcr.io location, prior to deleting them.

**Comment by viccuad** [comment]
Copied the old ones, together with their signatures, from the incorrect URIs (e.g: `ghcr.io/kubewarden/charts/kubewarden-crds/kubewarden-crds:v1.2.3`) to the correct URIs (e.g: `ghcr.io/kubewarden/charts/kubewarden-crds:v1.2.3`) with:
```
#!/usr/bin/env bash
set -ex
for CHART in kubewarden-crds kubewarden-controller kubewarden-defaults
do
    for TAG in $(crane ls ghcr.io/kubewarden/charts/"$CHART"/"$CHART")
    do
        crane copy \
           ghcr.io/kubewarden/charts/"$CHART"/"$CHART":"$TAG" \
           ghcr.io/kubewarden/charts/"$CHART":"$TAG"
    done
done
```

Obviously, the one tags don't have the number of downloads migrated from the old ones with the incorrect URI.
But at least we can delete the incorrect URI ones now.

I lack permissions to delete the incorrect URIs, moving this to blocked to not forget about it.

**Comment by flavio** [comment]
I've manually removed these charts from ghcr.io
