### ISSUE TITLE
Duplicated policy and image files in a release

### ISSUE THREAD

**Issue by jvanz** [kubewarden/helm-charts#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After recent changes in the release CI to add files with list of policies and images a [release](https://github.com/kubewarden/helm-charts/releases/tag/kubewarden-defaults-1.2.8) ended having two versions of the same file. 

### Expected Behavior

The release should have one file for the policy list and another one for the image list

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by viccuad** [comment]
This seems solved with the changes @jvanz did, https://github.com/kubewarden/helm-charts/releases/tag/kubewarden-defaults-1.4.0 is fine.
Closing!
