### ISSUE TITLE
Feature Request: automatically detect new versions of rancher-kubectl-builder and update charts

### ISSUE THREAD

**Issue by jvanz** [kubewarden/helm-charts#212]
### Is your feature request related to a problem?

We use the container image from the [rancher-kubectl-builder](https://github.com/kubewarden/rancher-kubectl-builder) repository in a pre-delete [job](https://github.com/kubewarden/helm-charts/blob/107eaa14a3ec696026675123777e7ed24c9184aa/charts/kubewarden-controller/values.yaml#L66-L70). We should write an updatecli script to automatically detect new version of the container image and update the Helm charts to used it.

### Solution you'd like

Write an updatecli to detect new versions of the [kubewarden/kubectl](https://github.com/kubewarden/rancher-kubectl-builder/pkgs/container/kubectl) container image and open a PR updating the version used in the Helm charts.

**Comment by viccuad** [comment]
This was implemented with https://github.com/kubewarden/helm-charts/pull/407.
