### ISSUE TITLE
Bug: `.Values.common.cattle.*` should be `.Values.global.cattle.*`

### ISSUE THREAD

**Issue by viccuad** [kubewarden/helm-charts#241]
As explained in https://confluence.suse.com/display/RMI/Feature+Charts+Helm+Requirements:

To allow for a custom registry to be used, add [this helper](https://github.com/rancher/charts/blob/b55e6ec01907964723942fdbd9f63b9afef7a1ed/packages/rancher-cis-benchmark/charts/templates/_helpers.tpl#L6-L12) and its [global value](https://github.com/rancher/charts/blob/b55e6ec01907964723942fdbd9f63b9afef7a1ed/packages/rancher-cis-benchmark/charts/values.yaml#L34-L36). You can see this template getting called in the format above.

We are mistakenly using `.common.cattle`, it should be `.global.cattle`.

### Acceptance criteria

- [x] For all charts, change `.Values.common.cattle.*` to `.Values.global.cattle.*`. This is a breaking change.
- [x] `.Values.global.cattle.systemDefaultRepository` should not have different behavior depending if the passed URL is http or https, as this contradicts the "ABI" of the Rancher docs. This means reverting https://github.com/kubewarden/helm-charts/pull/203. This is a breaking change.
- [x]  Update docs.kubewarden.io if needed.
- [x] Update the readmes of the charts if needed, they end in charts.kubewarden.io.
- [x] Check Airgap story docs and scripts.
- [x] Check deployment via Kubewarden UI.
- [x] Check Kubewarden UI airgap story.

**Comment by jvanz** [comment]
I've tested this change following the air-gap installation docs. It worked fine. However, I cannot test the charts in the UI. Because, afacis [here](https://github.com/kubewarden/ui/issues/385), this requires the Rancher `v2.7.5` version. Which are not available in none of the chart repositories:

```console
helm search repo --versions | grep rancher-alpha | head -3 
```

```console
helm search repo --versions | grep rancher-stable | head -3
rancher-stable/rancher                                  2.7.4           v2.7.4          Install Rancher Server to manage Kubernetes clu...
rancher-stable/rancher                                  2.7.3           v2.7.3          Install Rancher Server to manage Kubernetes clu...
rancher-stable/rancher                                  2.7.2           v2.7.2          Install Rancher Server to manage Kubernetes clu...
```

```console
 helm search repo --versions | grep rancher-latest | head -3
rancher-latest/rancher                                  2.7.4           v2.7.4          Install Rancher Server to manage Kubernetes clu...
rancher-latest/rancher                                  2.7.3           v2.7.3          Install Rancher Server to manage Kubernetes clu...
rancher-latest/rancher                                  2.7.2           v2.7.2          Install Rancher Server to manage Kubernetes clu...
```

Therefore, I'm moving this to block.

**Comment by viccuad** [comment]
I'm ok with not blocking on testing with Kubewarden UI, my main concern was not introducing regressions.

But given that this values are used on the airgap story, we should give @jordojordo a heads-up of their change, just in case.

**Comment by jvanz** [comment]
I've built a new version of the UI pointing to a new Helm chart version containing the fix from this issue. Then, I've forked the ui-plugins repo and add this new UI version on it. Therefore, I was able to test the installation on the UI. I've followed these steps:

1. Add a new extension repository in my Rancher manager `v2.7.5` . This feature is not enabled in previous version
1. Install new UI version witch uses the latest Helm chart version (with the fixes for this issue)



![Image](https://github.com/kubewarden/helm-charts/assets/1514798/eb5e40d7-5b36-42a7-bb16-82f6d81dadf8)


1. Install kubewarden-controller chart setting my personal github packages as the default container registry


![Image](https://github.com/kubewarden/helm-charts/assets/1514798/aec092b0-d229-4e7a-88d8-a0859f6a1e80)
![Image](https://github.com/kubewarden/helm-charts/assets/1514798/cb3cb44f-3983-44da-9e37-73d9f5512199)




1. Install kubewarden-defaults chart with recommended policies enabled and setting my personal github packages as the default container registry


![Image](https://github.com/kubewarden/helm-charts/assets/1514798/144654e3-c0d4-4386-9c74-96a85da40d0a)
![Image](https://github.com/kubewarden/helm-charts/assets/1514798/fcd99b3a-11fe-481d-b0da-ac4615c58bd6)



1. The installation goes fine,  all the resources get to active state using my "private" container images 


![Image](https://github.com/kubewarden/helm-charts/assets/1514798/7c994afe-3777-4d57-ae90-6a4d60a01067)
![Image](https://github.com/kubewarden/helm-charts/assets/1514798/aa73a2f1-9991-4044-b9ec-070eff71e4a1)




Therefore, I've consider this issue done. But keep in mind that there is an issue driven by @jordojordo  to further validate air gap installation on UI

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers if you agree with the previous comment, we can close this issue

**Comment by flavio** [comment]
I agree, we can close the issue
