### ISSUE TITLE
Artifact Hub shows RC images

### ISSUE THREAD

**Issue by flavio** [kubewarden/helm-charts#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When going to Artifact Hub's page of the kubewarden-controller helm chart, the `values.yml` file shown by the UI contains references to `1.7.0-rc1`.

I don't know if this is a Artifact Hub bug, or if we did something wrong.

### Expected Behavior

Release candidates should not be shown by Artifact Hub. Latest stable release should be provided

### Steps To Reproduce

- open https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller
- click on "default values" on the right sidebar
- inside of the search bar enter `image.tag`
- the code will show line 61, which currently holds `tag: v1.7.0-rc1`

### Anything else?

![image](https://github.com/kubewarden/helm-charts/assets/22728/da38cd58-b5ee-4aeb-8c49-5e36fd7fe390)

**Comment by viccuad** [comment]
It seems there's a helm Chart.yaml annotation that [marks them as pre-release](https://artifacthub.io/docs/topics/annotations/helm/): `artifacthub.io/prerelease `. We could add automation to patch the chart prior the release with that info.
