### ISSUE TITLE
catalog.cattle.io/auto-install annotation makes uninstall via Rancher fail

### ISSUE THREAD

**Issue by mpepping** [kubewarden/helm-charts#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Both the kubewarden-controller and kubewarden-defaults charts have Rancher specific annotations in the Charts.yaml file. The `catalog.cattle.io/auto-install` annotation ensures that an installation **via Rancher** automatically installs the kubewarden-crds chart. 

```yaml
annotations:
  [..]
  catalog.cattle.io/auto-install: kubewarden-crds=1.3.1 
```

1. https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/Chart.yaml#L36
1. https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-defaults/Chart.yaml#L36

This poses not to be an issue when **installing** the kubewarden-controller and kubewarden-defaults charts sequentially. Although the kubewarden-crds chart has a revision count of 2 after installing both kubewarden charts.

It is an issue when **uninstalling** the kubewarden-controller and kubewarden-defaults charts. This because, when removing either one, the kubewarden-crds chart will also automatically be uninstalled. With the Kubewarden CRD's missing it isn't possible to do a clean Helm uninstall of the remaining kubewarden chart. This will end in a "timed out waiting for the condition" error.

### Expected Behavior

The kubewarden-crds chart should be uninstalled as final chart, after kubewarden-controller and kubewarden-defaults are uninstalled. Not as an automatic uninstall when uninstalling either one.

See 'Anything else' for a proposed solution.

### Steps To Reproduce

It's quite easy to reproduce without Rancher, just using Helm:

```shell
$ helm -n cattle-kubewarden-system ls
NAME                         	NAMESPACE               	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
rancher-kubewarden-controller	cattle-kubewarden-system	1       	2023-08-02 14:40:03.481038547 +0000 UTC	deployed	kubewarden-controller-1.5.3	v1.6.0     
rancher-kubewarden-crds      	cattle-kubewarden-system	1       	2023-08-02 14:39:07.008744129 +0000 UTC	deployed	kubewarden-crds-1.3.1      	v1.6.0     
rancher-kubewarden-defaults  	cattle-kubewarden-system	1       	2023-08-02 14:39:54.741097139 +0000 UTC	deployed	kubewarden-defaults-1.6.1  	v1.6.0     

$ helm -n cattle-kubewarden-system uninstall rancher-kubewarden-defaults rancher-kubewarden-crds 
release "rancher-kubewarden-defaults" uninstalled
release "rancher-kubewarden-crds" uninstalled

$ helm -n cattle-kubewarden-system ls
NAME                         	NAMESPACE               	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
rancher-kubewarden-controller	cattle-kubewarden-system	1       	2023-08-02 14:40:03.481038547 +0000 UTC	deployed	kubewarden-controller-1.5.3	v1.6.0     


$ helm -n cattle-kubewarden-system uninstall rancher-kubewarden-controller
uninstall.go:95: [debug] uninstall: Deleting rancher-kubewarden-controller
client.go:128: [debug] creating 1 resource(s)
client.go:529: [debug] Watching for changes to Job rancher-kubewarden-controller with timeout of 5m0s
client.go:557: [debug] Add/Modify event for rancher-kubewarden-controller: ADDED
client.go:596: [debug] rancher-kubewarden-controller: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for rancher-kubewarden-controller: MODIFIED
client.go:596: [debug] rancher-kubewarden-controller: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for rancher-kubewarden-controller: MODIFIED
client.go:596: [debug] rancher-kubewarden-controller: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
[..]
Error: timed out waiting for the condition
```

### Environment

```markdown
- OS: Linux
- Architecture: x86
- Rancher v2.7.5
```

### Anything else?

A solution would be changing the `catalog.cattle.io/auto-install` annotation on kubewarden-defaults to auto-install kubewarden-controller, and leave the `catalog.cattle.io/auto-install` annotation on kubewarden-controller as is. 

This will leave one of the kubewarden charts in control of installing the CRD's, when Kubewarden is installed via Rancher.

**Comment by flavio** [comment]
Thanks for the detailed issue, we will look into that

**Comment by viccuad** [comment]
Hi, thanks for the report!

How are you uninstalling Kubewarden?
Tried with Rancher 2.7.5, and couldn't reproduce:

1. Installed Kubewarden UI extension,
2. Clicked the left bar, Kubewarden section,
3. Enabled Kubewarden charts repo via the Kubewarden UI,
4. Installed `kubewarden-controller` chart as `rancher-kubewarden-controller` via clicking "Install Kubewarden". This correctly installed `rancher-kubewarden-crds`.
5. Installed `kubewarden-defaults` via clicking on the "The default PolicyServer and policies are not installed, click the button below to begin installing this chart. See the [documentation](https://docs.kubewarden.io/quick-start#installation) for more information on installing charts. Install chart".
6. on Apps -> Installed Apps, deleted the `rancher-kubewarden-defaults` app, which corresponds to the chart. My `rancher-kubewarden-crds` keeps being present at its revision number.
7. I did the same for the `rancher-kubewarden-controller` , and `rancher-kubewarden-crds` still keeps being there.

Note that using Helm to delete CRDs is not supported, see [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations). We are following the method 2 (separate charts) listed there, but still, Rancher/Fleet doesn't have  the concept of chart of CRDs, and one needs to manually take care or uninstalling first all the charts with resources that come from CRDs, and then the CRDs. Updates may or may not be supported, depending if the CRDs and the controllers associated defined a version migration and a webhook conversion (Kubewarden does). 


From docs `catalog.cattle.io/auto-install` , and from the usage [other charts make of it](https://github.com/search?q=org%253Arancher+catalog.cattle.io%252Fauto-install&type=code), it seems it should be reserved for CRDs only.

Moreover, it is technically possible to install `kubewarden-defaults`, which rightfully depends on `kubewarden-crds` (as `kubewarden-defaults` deploys policies and a policy server), without deploying `kubewarden-controller`. This means the policies will be in status pending, and the policy server will not have an associated deployment.

**Comment by mpepping** [comment]
Thanks for the follow-up, @viccuad

We're using [the rancher2_app_v2 terraform resource](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2) for the Chart installations. It utilizes the Rancher API, just as the UI does. Both the controller and the defaults chart are installed sequentially using this Terraform resource. It honors the auto-install annotation as well, as the crds chart also gets installed.

I'll test the manual steps you described on our setup.

**Comment by viccuad** [comment]
@mpepping thanks for finding the terraform code!

I see, IMHO the behaviour of automatically uninstalling apps that got installed with `catalog.cattle.io/auto-install` is dangerous.
For example, you can have 2 separate charts both declare the same `catalog.cattle.io/auto-install: my-crds=1.0.0`. On uninstall of any of those charts, `my-crds` chart gets removed, breaking the remaining chart in the system as it is now missing the needed CRDs.

In the case of Kubewarden, we hit this, as we provide the CRDs chart and 2 charts that depend on it . It seems that the rest of the projects use 1 CRD chart and 1 chart more only (but several of them depend on monitoring for example, and uninstalling one will break the rest).

For the current approach of Terraform to work, it is needed to have a proper dependency management system for Helm charts and/or OCI artifacts, that knows about dependencies, optional dependencies, and their versions, and to delegate to it if a chart release is needed in the system anymore or can be scheduled for removal.

I see 2 possible workarounds:
- Kubewarden moves from having 3 charts (`kubewarden-crds`, `kubewarden-controller`, `kubewarden-defaults`) to only 2, merging the last two. This doesn't solve the issue with all the charts depending on monitoring or shared CRDs, and we wait for the next chart to hit this. This is considerable work for the Kubewarden team, and I don't think we will pursue it.
- Make the terraform behaviour on `catalog.cattle.io/auto-install` skippable on uninstall of chart `A`.
  It could be better improved if it would automatically skip a chart `B` specificed via `catalog.cattle.io/auto-install` , if that chart `B` has a `provides-gvr` for some CRDs that the chart `A` has in a `requires-gvr`. But this maybe doesn't fully solve transitive dependencies, and charts that provide or depend on several gvrs, as one cannot list several on those annotations.

**Comment by viccuad** [comment]
Opened https://github.com/rancher/terraform-provider-rancher2/issues/1195 to make them aware of the behavior.

Looking forward to your comment @mpepping, but I'm afraid from Kubewarden side, we can't do much more.

**Comment by mpepping** [comment]
Thanks @viccuad! Fully agree that it's something that should be addressed in the Terraform resource. I think we have a good example of when automatically uninstalling (crd) charts is dangerous. I'll follow up on the issue you've opened .. let's close this one.

For now we've integrated the 3rd workaround you suggested. That works, but yeah, maintaining forks because of deployment specifics is undesirable.
