### ISSUE TITLE
Allow triggering the chart update job using Github UI

### ISSUE THREAD

**Issue by jvanz** [kubewarden/helm-charts#307]
Update the [CI job](https://github.com/kubewarden/helm-charts/blob/main/.github/workflows/update-charts.yml) used to update the helm charts based on the releases in the Kubewarden components repositories, allowing users to trigger it using the Gihub UI. Therefore, it would be possible to continue the release process with no special curl commands and facilitate the job triggering after possible fixes to it.

**Comment by viccuad** [comment]
Opened https://github.com/kubewarden/helm-charts/pull/399, which I disliked. Converted it to draft and opened https://github.com/kubewarden/helm-charts/pull/400 which is based on it, plus contains some useful refactors that helped with testing.
