### ISSUE TITLE
Update to support controller's Webhooks

### ISSUE THREAD

**Issue by flavio** [kubewarden/helm-charts#31]
The new architecture relies on some controller Webhook to mutate/validate Kubewarden's resources. We have to ensure the helm chart creates the right RBAC permissions to allow the controller to work.

**Comment by raulcabello** [comment]
Closing this as there is no need to add RBAC permissions. We just need to add the webhooks and certificates and that will be done in https://github.com/kubewarden/helm-charts/issues/32
