### ISSUE TITLE
Remove cert-manager configuration

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/helm-charts#321]
### Is your feature request related to a problem?

Remove cert-manager related [configuration](https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/templates/cert-tls.yaml).

**Comment by flavio** [comment]
Hi, thanks for being interested on Kubewarden! Unfortunately this is quite a big task and @jvanz is already working on that. You can find more information about this epic inside of [this rfc](https://github.com/kubewarden/rfc/blob/main/rfc/0018-certificate-handling.md) document.

If you still want to help we can find some other smaller tasks that are ready to be taken

**Comment by TRISHAHALDER** [comment]
> Hi, thanks for being interested on Kubewarden! Unfortunately this is quite a big task and @jvanz is already working on that. You can find more information about this epic inside of [this rfc](https://github.com/kubewarden/rfc/blob/main/rfc/0018-certificate-handling.md) document.
> 
> If you still want to help we can find some other smaller tasks that are ready to be taken

Yeah,sure

**Comment by fabriziosestito** [comment]
Superseded by  #820
