### ISSUE TITLE
Update rancher-version annotation on controller chart

### ISSUE THREAD

**Issue by jordojordo** [kubewarden/helm-charts#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to install the Kubewarden Controller chart from the UI shows the latest available version as `1.1.1`

The annotation `catalog.cattle.io/rancher-version` that determines compatibility with the Rancher Manager is set to: `>= 2.6.0-0 <= 2.7.100-0`. 

### Expected Behavior

The latest charts should be installable for Rancher 2.8.

### Steps To Reproduce

1. Install Rancher Manager `v2.8-alpha2`
2. Add the Kubewarden helm charts: ` https://charts.kubewarden.io `
3. Attempt to install the Kubewarden controller chart
4. See the highest version available is `1.1.1` 

### Anything else?

![controller-chart](https://github.com/kubewarden/helm-charts/assets/40806497/3e499d63-2184-4a68-8ced-56356dbbe30a)

**Comment by viccuad** [comment]
the linked PR fixes it. I'm considering where to ship this, if in an immediate kubewarden-controller chart patch release, or wait for possible unrelated opentelemetry changes.

**Comment by jordojordo** [comment]
Thanks for the quick fix! Since we have some weeks before the 2.8 release, perhaps just wait until the opentelemetry changes are in?
