### ISSUE TITLE
Write release notes for the chart deploying the new architecture

### ISSUE THREAD

**Issue by flavio** [kubewarden/helm-charts#36]
We should write release notes for the helm chart version that introduces the new architecture.

The goals are:
* Explain what changed
* Provide manual instructions, if needed, for people upgrading from an older release

**Comment by raulcabello** [comment]
### What's new?
- Introduce a PolicyServer CRD that allow users to describe a Policy Server deployment
- ClusterAdmissionPolicy has a new PolicyStatus field which can be :
  - unscheduled, unschedulable, pending or active
- Separate helm chart for ClusterAdmissionPolicy and PolicyServer CRDs

### How to upgrade?

Unfortunately helm upgrade is not supported for this release. Uninstall previous kubewarden installation and delete the ClusterAdmissionPolicy CRD:

```shell
kubectl delete --all clusteradmissionpolicies.policies.kubewarden.io
helm uninstall --namespace kubewarden kubewarden-controller
kubectl delete namespace kubewarden
kubectl delete crd clusteradmissionpolicies.policies.kubewarden.io 
```
Then install kubewarden's new version:

```shell
 kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
 helm install --create-namespace -n kubewarden kubewarden-crds kubewarden/kubewarden-crds
 helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller
```

**Comment by flavio** [comment]
I've done some edits to your comment to fix the release notes. Good job!

**Comment by viccuad** [comment]
Should we be even more verbose? (I like overly verbose changelogs). I think it would be nice to mention:
- Drop of policyserver configmap (obviously) for configuring, moved to the CR. 
- Addition of `spec.policyserver` to ClusterAdmissionPolicy CRD, to target specific PolicyServers.
- Validation of CRs with validating and mutating webhooks.
- Finalizers.
- New condition `PolicyActive` for ClusterAdmissionPolicies, useful for `kubectl wait` for example.

Do we include Rego, OPA, Gatekeeper policies support at some point?

**Comment by flavio** [comment]
Rego support is already available, starting from this release: https://github.com/kubewarden/helm-charts/releases/tag/kubewarden-controller-0.2.3.

@viccuad I've applied your suggestions

**Comment by kkaempf** [comment]
Why is this not closed ?

**Comment by raulcabello** [comment]
@kkaempf we can close this. We still need to update the Release Notes once we do the release, but there is a separated card for that.
