### ISSUE TITLE
Automation should bump kubewarden-crds during major and minor releases.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/helm-charts#398]
In the current state of automation used to update the Helm charts, the `kubewarden-crds` Helm chart, is updated only when there is some CRD update. This is causing issues because the `appVersion` field among all the 3 charts should be kept in sync. Therefore, we need to update the automation scripts to bump the `kubewarden-crds` version and `appVersion` when a major/minor update happens. 

### Acceptance criteria
- Automation scripts used to bump the Helm chart versions should update the `kubewarden-crds` chart on major/minor updates even if the CRDs does not change.

**Comment by flavio** [comment]
This is really annoying, we should address that ASAP
