### ISSUE TITLE
Ensure the policy-server has enough rights to list contextual resources

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/helm-charts#4]
The `policy-server` today is fetching a list of [well known (and static) resources](https://github.com/kubewarden/policy-server/blob/052b68ddb86baf500965464e09d26ba22e29b3cb/crates/policy-evaluator/src/cluster_context.rs#L49-L53), being:

- Namespaces
- Services
- Ingresses

Until we make this configurable and extendable with custom resources, the `policy-server` needs to have enough rights in the Kubernetes cluster to list this resources, so context-aware policies can use this information to take contextual decisions (or perform contextual-aware mutations).

**Acceptance criteria**

- The `policy-server ` deployed through the controller started by the helm chart is able to list namespaces, services and ingresses in all namespaces.

**Comment by flavio** [comment]
I think this can be closed now, isn't it?

**Comment by ereslibre** [comment]
No, I'm still working on this. We have to grant access.

**Comment by ereslibre** [comment]
Despite the `serviceAccount` should be set now to `policy-server`, for some reason, the deployment created for the `policy-server` by the controller has the `default` SA yet. Looking into it.

**Comment by ereslibre** [comment]
https://github.com/kubewarden/helm-charts/pull/6 updated.
