### ISSUE TITLE
Automation: bump patch version by default

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/helm-charts#452]
### Is your feature request related to a problem?

The Helm chart release automation bumps the charts by a minor version.
Since in the most common scenario, we bump the container images version, we could instead default to a patch bump.
If the Helm chart was changed (values added/removed, configuration changes, etc..) we will need to bump the versions manually.

**Comment by viccuad** [comment]
The chart `version` informs about the features and compatibility of the chart WRT to upgrades. With that in mind, I believe:
- A new Kubewarden stack release should be a `version` minor bump.
- A breaking change on helm upgrade is a `version` major bump.
- A fix on the charts only (not necessarily with changes to the images, or other parts the Kubewarden stack) is a `version` patch bump.

This way, as a Kubernetes operator, one can know of the disruptiveness of the update by looking at the bump of `version`, and the extent of the features by looking at the bump of `appVersion`. This should be consistent with the [RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0007-kubewarden-versioning.md#helm-charts).

**Comment by flavio** [comment]
Closing, we've just agreed it's fine to bump the minor version
