### ISSUE TITLE
Add missing README file

### ISSUE THREAD

**Issue by flavio** [kubewarden/helm-charts#50]
On Artifact Hub, neither the [kubewarden-controller](https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller) nor the [kubewarden-crds](https://artifacthub.io/packages/helm/kubewarden/kubewarden-crds) charts have a README.

## Acceptance criteria

* [ ] Add README to kubewarden-controller helm chart
* [ ] Add README to kubewarden-crd helm chart

**Comment by viccuad** [comment]
Note the readmes published on Artifact Hub are the one inside the helm chart proper (`charts/kubewarden-controller/README.md` for example). We could split `charts/README.md` into both. Then concat them when running the GH Action workflow in this repo that builds and publishes https://charts.kubewarden.io.
