### ISSUE TITLE
Feature Request: Support ImagePullsecret for PolicyServer (Deployment)

### ISSUE THREAD

**Issue by CrimsonRot** [kubewarden/helm-charts#568]
### Is your feature request related to a problem?

We have a private registry which only allows pulling images with authentication.
PolicyServer seems to not provide the possibility to use our own credentials for the create pod or deployment.

After installing the policy server with custom values for imagePullSecrets a imagePullBackoff error occurs.

`apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-10-25T08:49:18Z"
  generateName: policy-server-default-855669b6c8-
  labels:
    app: kubewarden-policy-server-default
    kubewarden/config-version: "2465879"
    kubewarden/policy-server: default
    pod-template-hash: 855669b6c8
  name: policy-server-default-855669b6c8-hxbsz
  namespace: kubewarden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: policy-server-default-855669b6c8
    uid: 130dc418-ead5-4f17-9f62-e45f17a008e0
  resourceVersion: "3172235"
  uid: feb2b2a7-dc23-4246-82f8-31d6239b9a3c
spec:
  affinity: {}
  containers:
  - env:
    - name: KUBEWARDEN_CERT_FILE
      value: /pki/tls.crt
    - name: KUBEWARDEN_KEY_FILE
      value: /pki/tls.key
    - name: KUBEWARDEN_PORT
      value: "8443"
    - name: KUBEWARDEN_POLICIES_DOWNLOAD_DIR
      value: /tmp
    - name: KUBEWARDEN_POLICIES
      value: /config/policies.yml
    - name: KUBEWARDEN_SIGSTORE_CACHE_DIR
      value: /tmp/sigstore-data
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
    - name: KUBEWARDEN_ALWAYS_ACCEPT_ADMISSION_REVIEWS_ON_NAMESPACE
      value: kubewarden
    - name: KUBEWARDEN_DOCKER_CONFIG_JSON_PATH
      value: /home/kubewarden/.docker
    image: private/ghcr/kubewarden/policy-server:v1.17.0
    imagePullPolicy: IfNotPresent
    name: policy-server-default
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readiness
        port: 8443
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /pki
      name: certs
      readOnly: true
    - mountPath: /config
      name: policies
      readOnly: true
    - mountPath: /tmp
      name: policy-store
    - mountPath: /home/kubewarden/.docker
      name: imagepullsecret
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nk9gb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: policy-server
  serviceAccountName: policy-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: policy-store
  - name: certs
    secret:
      defaultMode: 420
      secretName: policy-server-default
  - configMap:
      defaultMode: 420
      items:
      - key: policies.yml
        path: policies.yml
      name: policy-server-default
    name: policies
  - name: imagepullsecret
    secret:
      defaultMode: 420
      items:
      - key: .dockerconfigjson
        path: config.json
      secretName: mySecret
  - name: kube-api-access-nk9gb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
`

The imagepull secret is only as Volume so the policies can be pulled but not for the container itself

### Solution you'd like

Add the possibilitie to add imagepullsecrets for deployment/Image

**Comment by viccuad** [comment]
Hi,

If I'm understanding it correctly it seems that you are trying to edit the policy-server Deployment, but these Deployments are mainly managed by the Kubewarden controller.

The correct way to do this is to configure the PolicyServer CRD, by setting the PolicyServer Custom Resource `spec.imagePullSecret`.

You can do this per each PolicyServer.
For the `default` PolicyServer that gets created with the `kubewarden-defaults` helm chart, since it is managed via the helm chart, it is recommended to set it via the helm chart.

See: https://docs.kubewarden.io/howtos/policy-servers/private-registry

**Comment by CrimsonRot** [comment]
Hi,

I did exactly this but the secret seems to only be used to pull the policies but not the image itself.
Therefore the image `private/ghcr/kubewarden/policy-server:v1.17.0 ` can't be pulled by the Kubernetes Cluster and no policiyServer can be created

**Comment by viccuad** [comment]
Oh, I understand now. Yes, that's correct, this configures the PolicyServers to pull the policies.

If you want to configure the controller so it can pull images from a private registry, that's done in the `kubewarden-controller` helm chart, with `--set imagePullSecrets`  (see [values.yaml](https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/values.yaml#L109)).

I hope this is what you are looking for.
