### ISSUE TITLE
Update OTEL questions to work with UI

### ISSUE THREAD

**Issue by kravciak** [kubewarden/helm-charts#597]
Things to fix:
 - [ ] [UI does not detect enabled telemetry](https://github.com/rancher/kubewarden-ui/issues/1006)
 - [x] [`Sidecar` UI config shows all fields, it's not obvious which belong to tracing / metrics (tracing port under enable metrics section)](https://github.com/kubewarden/helm-charts/pull/598)
 - [x] `Custom` UI config shows cert fields and hides metrics port, is it meant just for custom certificate config?
 - [ ] UI upgrade does not show any mention that it's breaking change, tracing/metrics stop working

## Original UI workflow:

https://github.com/user-attachments/assets/a3a7da79-2cd1-4986-b060-6a3deead7b6c

## Current state in RC1:

Telemetry settings do not make sense:

https://github.com/user-attachments/assets/35674cec-8917-450a-b248-04c0a0138eb0

Telemetry enablement not detected:

![Screenshot from 2024-12-16 11-34-31](https://github.com/user-attachments/assets/07f3f3f0-3838-42a5-a9be-623d989c4d55)

**Comment by viccuad** [comment]
> UI upgrade does not show any mention that it's breaking change, tracing/metrics stop working

One could argue that the breaking change is signified by the major version upgrade of the chart. I'm not sure if from Kubewarden UI we can do anything, as the update happens via the normal Rancher UI charts/applications.

**Comment by jvanz** [comment]
> Custom UI config shows cert fields and hides metrics port, is it meant just for custom certificate config?

Yes. The metrics port field is used to configure the prometheus exporter port when the sidecar collector is enable. There is not need to have this port for the custom configuration. It's up to the user to proper configure the collector used.

**Comment by jvanz** [comment]
> Sidecar UI config shows all fields, it's not obvious which belong to tracing / metrics (tracing port under enable metrics section)

Let me see if I can change the `show_if` configuration to change this. I'm not sure if it's doable. If it's not, I'll add something note in the field description.

**Comment by kravciak** [comment]
Closing, PRs fixing the issues are merged.
