### ISSUE TITLE
Sign Helm charts

### ISSUE THREAD

**Issue by jvanz** [kubewarden/helm-charts#92]
To ensure that the Kubewarden users are using the right software versions and binaries from the Kubewarden team, we should sign the Helm charts using Sigtore infrastructure. 

See more at [threat kubewarden threat #1](https://github.com/kubewarden/rfc/blob/main/rfc/0006-threat-model.md#threat-kubewarden-id-1---bootstrapping-of-trust-for-admission-controller)

**NOTE:** This is an issue created from RFC discussing the admission control threat model. It's created to allow the Kubewarden team discuss the proposed mitigation further and start to work on each actionable item when possible

**Comment by jvanz** [comment]
After a research and a quick talk with @vicuad, I think we have two options:

Option 1: Use keyless to sign Helm charts

```
$ helm package kubewarden-defaults
$ helm push kubewarden-defaults-0.1.3.tgz [oci://ghcr.io/viccuad/charts/kubewarden-defaults](oci://ghcr.io/viccuad/charts/kubewarden-defaults)
$ COSIGN_EXPERIMENTAL=1 cosign sign ghcr.io/viccuad/charts/kubewarden-defaults/kubewarden-defaults:0.1.3
$ COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/viccuad/charts/kubewarden-defaults/kubewarden-defaults:0.1.3 | jq
```

Option 2:  use the [Helm plugin](https://github.com/sigstore/helm-sigstore) provided by the Sigstore project to upload the signatures to Rekor. The chart is signed using the signing options in the [Helm command line](https://helm.sh/docs/topics/provenance/). And then the signatures are upload to Rekor using the Helm plugin. See the [documentation](https://github.com/sigstore/helm-sigstore/blob/main/USAGE.md) to check the commands to sign, upload ans check Helm chart signatures

Reference

https://helm.sh/docs/topics/provenance/
https://github.com/sigstore/helm-sigstore
https://github.com/sigstore/helm-sigstore/blob/main/USAGE.md

**Comment by jvanz** [comment]
If we decided to sign the Helm chart using the cosign keyless feature, we will not be able to verify the signature using the sigstore  helm plugin :

```console
helm sigstore search kubewarden-defaults-0.1.3.tgz                                                                                                                                       
could not load provenance file kubewarden-defaults-0.1.3.tgz.prov: stat kubewarden-defaults-0.1.3.tgz.prov: no such file or directory
Error: plugin "sigstore" exited with error
```

The plugin needs the [provenance](https://helm.sh/docs/topics/provenance/) file to check the chart signatures. Which is not generated by  the keyless signing.

**Comment by jvanz** [comment]
I moved this issue to "Pending review" to show the options to other team members.

**Comment by jvanz** [comment]
It would be nice to add a feature to the Sigstore plugin to allow it verify keyless signed charts. It sounds a good feature to have. But I do not have the knowledge to know if this is feasible or not. We can start a discussion there and see what happens. Maybe we can help adding this functionality.

**Comment by flavio** [comment]
From my understanding, option number two (the one leveraging the helm sigstore plugin) requires to have a "helm provenance" file. To produce this file we would need a GPG keypair. There's no way around that.

I think I prefer to go with the first option, the one that allows us to use keyless. The only downside is that verification relies on `cosign` command, instead of something bundled with the `helm` command. However, this has the advantage of not requiring us to manage a private GPG key

**Comment by raulcabello** [comment]
I also prefer option 1, so we don't a GPG keypair. However we would need to store our helm charts in an OCI registry for option 1 to work, right? As far as I know we are currently using [helm-chart-releaser](https://github.com/helm/chart-releaser-action) that turns our GitHub project into a self-hosted Helm chart repo.

**Comment by flavio** [comment]
I think we got a consensus, to recap:

* We are going to keep publishing our helm charts using the already existing pipeline
* On the side, we will also create a new pipeline that signs the helm charts with sigstore and pushes the helm chart to an OCI registry

@jvanz do you want to handle the 2nd point or should we create a new dedicated card?
